name: Create Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      release_notes:
        description: 'Optional custom changelog (use \\n for new lines)'
        required: false
        type: string
      dry_run:
        description: 'Dry run (build & compute version only, skip commit/tag/publish/release)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Calculate new version
        id: version
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"
          
          IFS='.' read -ra VERSION_PARTS <<< "$current_version"
          major=${VERSION_PARTS[0]}
          minor=${VERSION_PARTS[1]}
          patch=${VERSION_PARTS[2]}
          
          case "${{ github.event.inputs.bump_type }}" in
            "major")
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            "minor")
              minor=$((minor + 1))
              patch=0
              ;;
            "patch")
              patch=$((patch + 1))
              ;;
          esac
          
          new_version="${major}.${minor}.${patch}"
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Build package
        run: pnpm build

      - name: Commit version change
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to v${{ steps.version.outputs.version }}"

      - name: Create and push tag
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
          git push origin HEAD
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Publish to npm
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          NOTES_INPUT="${{ github.event.inputs.release_notes }}"
          # Convert literal \n sequences into actual newlines (user can input escaped newlines)
          NOTES_INPUT="${NOTES_INPUT//\\n/$'\n'}"
          if [ -z "$NOTES_INPUT" ]; then
            printf "## What's Changed\n\n**Full Changelog**: https://github.com/${{ github.repository }}/commits/v${{ steps.version.outputs.version }}\n" > RELEASE_NOTES.md
          else
            printf "%s\n\n**Full Changelog**: https://github.com/${{ github.repository }}/commits/v${{ steps.version.outputs.version }}\n" "$NOTES_INPUT" > RELEASE_NOTES.md
          fi

          echo "---- Release Notes ----"
          cat RELEASE_NOTES.md

          gh release create "v${{ steps.version.outputs.version }}" \
            --title "Release v${{ steps.version.outputs.version }}" \
            --notes-file RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Preview release notes (dry run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          NOTES_INPUT="${{ github.event.inputs.release_notes }}"
          NOTES_INPUT="${NOTES_INPUT//\\n/$'\n'}"
          if [ -z "$NOTES_INPUT" ]; then
            printf "## What's Changed\n\n**Full Changelog**: https://github.com/${{ github.repository }}/commits/v${{ steps.version.outputs.version }}\n" > RELEASE_NOTES.md
          else
            printf "%s\n\n**Full Changelog**: https://github.com/${{ github.repository }}/commits/v${{ steps.version.outputs.version }}\n" "$NOTES_INPUT" > RELEASE_NOTES.md
          fi

          echo "---- (Dry Run) Release Notes Preview ----"
          cat RELEASE_NOTES.md
          echo "----------------------------------------"

      - name: Dry run summary
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          echo "Dry run mode enabled."
          echo "Calculated new version: v${{ steps.version.outputs.version }}"
          echo "Build completed. Skipped commit, tag creation, push, npm publish, and GitHub release."
